import { useState } from 'react';
import { MaterialIcon } from '../../components/ui/MaterialIcon';

export function DoctorNewVoiceSessionPage() {
  const [appointment, setAppointment] = useState('APT-DEMO-01');
  const [purpose, setPurpose] = useState('Scheduled Consultation');
  const [consent, setConsent] = useState(false);
  const [notice, setNotice] = useState('');

  return <div className="doctor-page doctor-new-voice-page"><a className="doctor-new-voice-page__back" href="/doctor/voice-sessions"><MaterialIcon name="arrow_back" /> Voice Sessions / الجلسات الصوتية</a><header className="doctor-new-voice-page__heading"><div><span className="doctor-voice-list-page__eyebrow"><MaterialIcon name="mic" /> New Synthetic Session</span><h1>New Voice Session <span>/ جلسة صوتية جديدة</span></h1><p>Prepare a local demonstration session. This page never accesses a microphone or records audio.</p></div><span className="doctor-new-voice-page__boundary"><MaterialIcon name="shield" /> Demo-only local session</span></header><div className="doctor-new-voice-page__grid"><section className="doctor-patient-card doctor-new-voice-page__form"><h2>Encounter Context</h2><label htmlFor="voice-appointment">Appointment / الموعد<select id="voice-appointment" value={appointment} onChange={(event) => setAppointment(event.target.value)}><option value="APT-DEMO-01">APT-DEMO-01 • Follow-Up Lab Review</option><option value="APT-DEMO-02">APT-DEMO-02 • Scheduled Consultation</option><option value="APT-DEMO-03">APT-DEMO-03 • Routine Review</option></select></label><label htmlFor="voice-purpose">Session purpose / غرض الجلسة<select id="voice-purpose" value={purpose} onChange={(event) => setPurpose(event.target.value)}><option>Scheduled Consultation</option><option>Follow-Up Lab Review</option><option>Clinical Documentation Review</option></select></label><div className="doctor-new-voice-page__patient"><MaterialIcon name="person" /><div><strong>[Patient Name]</strong><span>Patient ID: PATIENT-DEMO-01</span><small>Encounter binding: {appointment}</small></div></div><label className="doctor-new-voice-page__consent"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /> <span>Confirm this synthetic session is authorized for demonstration UI only. No legal consent, recording compliance, or clinical commitment is represented.</span></label><div className="doctor-new-voice-page__actions"><a href="/doctor/voice-sessions">Cancel Session</a><button className="is-primary" type="button" disabled={!consent} onClick={() => setNotice('Demo only - synthetic session prepared. No audio recording started.')}><MaterialIcon name="mic" /> Start Demo Session</button></div></section><aside className="doctor-new-voice-page__side"><section className="doctor-patient-card"><h2><MaterialIcon name="tune" /> Input Settings</h2><p>Language: Bilingual mixed (AR-EG / EN)</p><p>Transcript: Synthetic deterministic content</p><p>Retention: None</p></section><section className="doctor-patient-card doctor-new-voice-page__warning"><MaterialIcon name="warning" /><strong>Audio safety boundary</strong><p>Start Demo Session changes local interface state only. It does not invoke microphone, audio, speech, or network APIs.</p></section></aside></div>{notice && <p className="doctor-new-voice-page__notice" role="status">{notice}</p>}</div>;
}
